/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsLegoRouteImport } from './routes/lessons.lego'
import { Route as LessonsArduinoRouteImport } from './routes/lessons.arduino'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLegoRoute = LessonsLegoRouteImport.update({
  id: '/lessons/lego',
  path: '/lessons/lego',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsArduinoRoute = LessonsArduinoRouteImport.update({
  id: '/lessons/arduino',
  path: '/lessons/arduino',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lessons/arduino': typeof LessonsArduinoRoute
  '/lessons/lego': typeof LessonsLegoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lessons/arduino': typeof LessonsArduinoRoute
  '/lessons/lego': typeof LessonsLegoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lessons/arduino': typeof LessonsArduinoRoute
  '/lessons/lego': typeof LessonsLegoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/leaderboard'
    | '/lessons/arduino'
    | '/lessons/lego'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/leaderboard'
    | '/lessons/arduino'
    | '/lessons/lego'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/leaderboard'
    | '/lessons/arduino'
    | '/lessons/lego'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LessonsArduinoRoute: typeof LessonsArduinoRoute
  LessonsLegoRoute: typeof LessonsLegoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/lego': {
      id: '/lessons/lego'
      path: '/lessons/lego'
      fullPath: '/lessons/lego'
      preLoaderRoute: typeof LessonsLegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/arduino': {
      id: '/lessons/arduino'
      path: '/lessons/arduino'
      fullPath: '/lessons/arduino'
      preLoaderRoute: typeof LessonsArduinoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  LeaderboardRoute: LeaderboardRoute,
  LessonsArduinoRoute: LessonsArduinoRoute,
  LessonsLegoRoute: LessonsLegoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
