/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsLegoRouteImport } from './routes/lessons.lego'
import { Route as LessonsArduinoRouteImport } from './routes/lessons.arduino'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLegoRoute = LessonsLegoRouteImport.update({
  id: '/lessons/lego',
  path: '/lessons/lego',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsArduinoRoute = LessonsArduinoRouteImport.update({
  id: '/lessons/arduino',
  path: '/lessons/arduino',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons/arduino': typeof LessonsArduinoRoute
  '/lessons/lego': typeof LessonsLegoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons/arduino': typeof LessonsArduinoRoute
  '/lessons/lego': typeof LessonsLegoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons/arduino': typeof LessonsArduinoRoute
  '/lessons/lego': typeof LessonsLegoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lessons/arduino' | '/lessons/lego'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lessons/arduino' | '/lessons/lego'
  id: '__root__' | '/' | '/lessons/arduino' | '/lessons/lego'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsArduinoRoute: typeof LessonsArduinoRoute
  LessonsLegoRoute: typeof LessonsLegoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/lego': {
      id: '/lessons/lego'
      path: '/lessons/lego'
      fullPath: '/lessons/lego'
      preLoaderRoute: typeof LessonsLegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/arduino': {
      id: '/lessons/arduino'
      path: '/lessons/arduino'
      fullPath: '/lessons/arduino'
      preLoaderRoute: typeof LessonsArduinoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsArduinoRoute: LessonsArduinoRoute,
  LessonsLegoRoute: LessonsLegoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
